### PR TITLE
Fix version numbers

### PR DESCRIPTION
**Pull request by schrockn**
Hello! Thanks for putting up this docker image. I encountered some errors while getting this setup stemming from the version update from parquet tools.

I still cannot get this working as I get the following:

```
java -jar parquet-tools-1.10.1-SNAPSHOT.jar org.apache.parquet.cli.Main
Unknown command: org.apache.parquet.cli.Main
```

I'm on a mac with the following java version.

```
java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

I don't know much about the java ecosytem so I was hoping you might have the solution off the top of your head. Thanks!

### CODE REVIEW

**Comment by gg7** [comment]
Hey,

Thanks for letting me know about the new versions.

> `java -jar parquet-tools-1.10.1-SNAPSHOT.jar org.apache.parquet.cli.Main`
> `Unknown command: org.apache.parquet.cli.Main`

`parquet-tools` and `parquet-cli` are different. Apparently I forgot to include any examples for `parquet-tools`, apologies.

Try `java -jar parquet-tools-1.10.1-SNAPSHOT.jar`.

`parquet-tools` examples with files present locally:

```
alias parquet-tools='java -jar ~/bin/parquet-tools-1.10.1-SNAPSHOT.jar'
parquet-tools schema sample.parquet | less
parquet-tools cat sample.parquet | less
parquet-tools head -n5 sample.parquet | less
parquet-tools meta sample.parquet | less
```

`parquet-tools` examples with files present on HDFS:

```
~/hadoop/hadoop-2.8.2/bin/hadoop jar ~/parquet-tools-1.9.1-SNAPSHOT.jar meta 'hdfs://your-server/what/ever.snappy.parquet'
```

**Comment by gg7** [comment]
I will push several commits and update the readme in a bit.

**Comment by schrockn** [comment]
Thanks so much!

**Comment by gg7** [comment]
@schrockn Improvements pushed.

**Comment by schrockn** [comment]
awesome thanks!

**Pull request merged**
